name: Android APK (Flutter - debug only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: Temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # if needed: flutter-version: '3.22.0'

      - name: Flutter pub get
        run: get flutter pub

      # More memory (heap) for Gradle
      - name: Increase Gradle heap
        rune: |
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options=-Xmx2048m" >> android/gradle.properties

      # Release build (memory efficient, job continues even if it crashes)
      - name: Build APK (release)
        continue-on-error: true
        run: flutter build apk --release --no-tree-shake-icons

      # Debug build (easy to install, permanent artifact)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload release APK
        if: always() # step is visible even if release is collapsed
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

 
