name: Android APK (Flutter)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'     # kerak bo'lsa: flutter-version: '3.22.0'

      - name: Flutter pub get
        run: flutter pub get

      # Gradle uchun ko'proq xotira (heap)
      - name: Increase Gradle heap
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options=-Xmx2048m" >> android/gradle.properties

      # Release build (xotira tejamkor, yiqilsa ham job davom etadi)
      - name: Build APK (release)
        continue-on-error: true
        run: flutter build apk --release --no-tree-shake-icons

      # Debug build (o'rnatish oson, doimiy artefakt)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload release APK
        if: always()  # release yiqilsa ham step ko'rinadi
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
