name: Android APK (Flutter - debug only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      # More memory (heap) for Gradle
      - name: Increase Gradle heap
        run: echo "org.gradle.jvmargs=-Xmx4096m -Xms512m -XX:MaxMetaspaceSize=512m" >> gradle.properties

      # Debug build (easy to install, permanent artifact)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
